### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by thomas-tcl** [CaTeNdrE/gas-gmail-add-parent-of-nested-label#1]
Love the idea behind the project and what you're trying to fix. 

On line 131 I get: 

`Error	
TypeError: Cannot read property 'id' of undefined
addParentLabel	@ Add Parent Labels.gs:131`

**Comment by CaTeNdrE** [comment]
The code posted is very out of date.  I have modified significantly.  I'll update code shortly.

**Comment by CaTeNdrE** [comment]
@thomas-tcl the code has been updated significantly.  Let me know if you experience any other issues.
