### ISSUE TITLE
Exclude top level labels?

### ISSUE THREAD

**Issue by citydelver** [CaTeNdrE/gas-gmail-add-parent-of-nested-label#2]
Hello, I would like to use your script but excluding top level labels, is that possible?

**Use case**

Consider the following labels:

Places
Places/UK
Places/UK/London
Places/US
Places/US/NY
Places/US/LA
People
People/Family
People/Friends
People/Friends/Club
People/Friends/University
People/Work
People/Work/CompanyA
People/Work/CompanyB
Etc
Etc/Purchases
Etc/Rent
Etc/Rent/HouseA
Etc/Rent/HouseB

I would like to have the script add "UK" to mails labeled "London" and add "US" to mails tagged "NY" or "LA" but not add the "useless" label "Places" to them. And the same for "People" and "Etc" (especially for avoiding the visual clutter of having those labels shown in each row of the inbox view, for example).

I.e., I would like the script to apply all parent labels except for the top level one. Is that possible? I'd love to have your help if you could spare some minutes to help a stranger from the internet :)

**Comment by CaTeNdrE** [comment]
@citydelver the updated code allows setting a specific label to ignore   (Labels Skip List) and/or skipping all the descendants of a label (Offspring Skip List).  Let me know if you experience any issues.
